import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import Link from "next/link"
import fetch from 'node-fetch'
import Post from "../components/blog/post"

const Home = ({ posts}) => {
  return (
    <div /*className={styles.container}*/>
      <Head>
        <title>Home | {process.env.SITE_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>
          Diego&apos;s blog
        </h1>
        <div className="ed-grid m-grid-3 row-gap">
          {
            posts.map(p => <Post key={p.id} post={p} />)
          }
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  
  const res = await fetch(`${process.env.API_BLOG}posts`)

  const posts = await res.json()

  return{
    props: {
      posts
    }
  }
}

export default Home
