import Head from 'next/head'
// import styles from '../styles/Home.module.css'
import fetch from 'node-fetch'
import Post from "../components/blog/post"
import { NextSeo } from 'next-seo'

const Home = ({ posts}) => {
  return (
    <div /*className={styles.container}*/>
      <NextSeo
        title={`Home | ${process.env.SITE_NAME}`}
        // meta name="description" content="Generated by create next app"
        description="Esta es la pagina de inicion del blog de diego"
        openGraph={{
          site_name: process.env.SITE_NAME,
          url: process.env.SITE_URL,
          title: `Home | ${process.env.SITE_NAME}`,
          description: "Esta es la pagina de inicion del blog de diego",
          images: [
            {
              url: "https://ed.team/static/images/logo/isotipo-color.svg",
              width: 720,
              height: 720,
              alt: "logo de EDTeam"
            }
          ]
        }}
        twitter={{
          handle: "@Zyx_68",
          site: "@Zyx_68",
          cardType: "summary_lange_image"
        }}
      />
      <main>
        <h1>
          Diego&apos;s blog
        </h1>
        <div className="ed-grid m-grid-3 row-gap">
          {
            posts.map(p => <Post key={p.id} post={p} />)
          }
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  
  const res = await fetch(`${process.env.API_BLOG}posts`)

  const posts = await res.json()

  return{
    props: {
      posts
    }
  }
}

export default Home
